// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import IsActiveController from './is_active_controller'
import SplitsController from './splits_controller'

application.register('is_active', IsActiveController)
application.register('splits', SplitsController)
