require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - bin/*
    - config.ru
    - Rakefile
    - db/schema.rb
    - db/data_schema.rb
    - vendor/**/*
    - node_modules/**/*

Rails/RakeEnvironment:
  Enabled: false

# TODO: if/when we localize we'll need to unwind this, but
# it isn't worth dealing with at this stage
Rails/I18nLocaleTexts:
  Enabled: false

Rails/ReversibleMigration:
  Exclude:
    - 'db/data/**'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/data/**/*'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never
  Exclude:
    - lib/tasks/**/*

Style/FormatStringToken:
  EnforcedStyle: template

# Lint/AmbiguousBlockAssociation:
#   Exclude:
#     - spec/**/*

Style/ModuleFunction:
  EnforcedStyle: extend_self

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'

# Doesn't always make things easier to read
Style/GuardClause:
  Enabled: false

# I like this style but it causes bugs. See:
#   https://github.com/thoughtbot/factory_bot/issues/698
#   https://github.com/aha-app/rubocop-aha/pull/4
Style/SymbolProc:
  Enabled: false

# SIZE / COMPLEXITY

Metrics/AbcSize:
  # ABC is too strict about mass assignment, e.g. ActiveRecord.create!(<lots of params>)
  Max: 40
  Exclude:
    - db/migrate/*
    - db/data/*

Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - db/migrate/*
    - db/data/*

Metrics/ModuleLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'hash']
  Exclude:
    - spec/support/**/*

Metrics/BlockLength:
  CountAsOne: ['array', 'heredoc', 'hash']
  Exclude:
    - config/routes.rb
    - config/environments/*
    - config/initializers/*
    - spec/**/*_spec.rb
    - spec/factories/**/*.rb
    - db/migrate/*
    - db/data/*
    - lib/tasks/**/*

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 7

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    # This is for matching comments generated by the annotate gem
    - '#  [^ ]+ +\:(integer|bigint|string|text|datetime|date|boolean|float|decimal|json|jsob)'

Style/Documentation:
  Exclude:
    - db/data/*
    - db/migrate/*
    - config/application.rb
    - spec/**/*
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - app/jobs/application_job.rb
    - app/controllers/**/*
    - app/serializers/**/*
