version: "3.3"

services:
  nginx:
    build:
      context: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - acme_challenge:/var/www/_letsencrypt
    networks:
      - app
    restart: always
  letsencrypt:
    image: certbot/certbot
    command: sh -c "certbot certonly --expand --webroot -w /tmp/acme_challenge -d app.fourth-strike.com --text --agree-tos --email info@fourth-strike.com --rsa-key-size 4096 --verbose --non-interactive --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt
      - acme_challenge:/tmp/acme_challenge
    environment:
      - TERM=xterm
    restart: "no"
  # chrome:
  #   image: zenika/alpine-chrome
  #   command: --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 https://www.chromestatus.com/
  #   ports:
  #     - 9222:9222
  #   networks:
  #     - app
  #   restart: unless-stopped
  app:
    # build: .
    image: registry.digitalocean.com/fourth-strike/app:latest
    ports:
      - 3000:3000
    volumes:
      - storage:/rails/storage
      # This works around a well-known quirk:
      # https://ieftimov.com/posts/docker-compose-stray-pids-rails-beyond/
      - type: tmpfs
        target: /rails/tmp/pids
        tmpfs:
          size: "524288" # 512kb
          mode: 01777 # make sure it's rw by the rails user
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_LEVEL=info
      - RAILS_LOG_TO_STDOUT=true
      - HOSTNAME=app.fourth-strike.net
      - RAILS_MIN_THREADS=1
      # - CHROME_URL=http://chrome:9222
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - RAILS_MASTER_KEY
    networks:
      - app
    restart: always

volumes:
  storage:
    external: true
  letsencrypt:
    external: false
  acme_challenge:
    external: false

networks:
  app:
    driver: bridge
