services:
  proxy:
    build:
      context: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app
    restart: always
  app:
    # build: .
    image: rabidaudio/fourth-strike:latest
    ports:
      - 3000:3000
    volumes:
      - storage:/rails/storage
      - cache:/rails/tmp/cache
      # This works around a well-known quirk:
      # https://ieftimov.com/posts/docker-compose-stray-pids-rails-beyond/
      - type: tmpfs
        target: /rails/tmp/pids
        tmpfs:
          size: "524288" # 512kb
          mode: 01777 # make sure it's rw by the rails user
    networks:
      - app
    restart: always
    environment: &appenv
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_LEVEL=info
      - RAILS_LOG_TO_STDOUT=true
      - HOSTNAME=app.fourth-strike.com
      - RAILS_MIN_THREADS=1
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - RAILS_MASTER_KEY
  worker:
    # build: .
    image: rabidaudio/fourth-strike:latest
    volumes:
      - storage:/rails/storage
      - cache:/rails/tmp/cache
    networks:
      - app
    restart: always
    command: bundle exec rake jobs:work
    environment: *appenv

volumes:
  storage:
    external: true
  proxy:
    external: false
  cache:
    external: true

networks:
  app:
    driver: bridge
