version: "3.3"

services:
  nginx:
    build:
      context: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - acme_challenge:/var/www/_letsencrypt
    networks:
      - app
    restart: always
  letsencrypt:
    image: certbot/certbot
    command: sh -c "certbot certonly --expand --webroot -w /tmp/acme_challenge -d app.fourth-strike.com --text --agree-tos --email info@fourth-strike.com --rsa-key-size 4096 --verbose --non-interactive --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - letsencrypt:/etc/letsencrypt
      - acme_challenge:/tmp/acme_challenge
    environment:
      - TERM=xterm
    restart: "no"
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - storage:/rails/storage
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_LEVEL=info
      - RAILS_LOG_TO_STDOUT=true
      - HOSTNAME=app.fourth-strike.net
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - RAILS_MASTER_KEY
    networks:
      - app
    restart: always

volumes:
  storage:
    external: true
  letsencrypt:
    external: false
  acme_challenge:
    external: false

networks:
  app:
    driver: bridge
