organization_name: Fourth Strike
operating_currency: USD
organization_cut:
  digital: 0.15
  merch: 0.30
services_rendered:
  hourly_rate: 15.00 # USD/hr
payout_at: 42.00 # USD
paypal:
  incoming_addresses:
    - seattlegarages@gmail.com
    - info@fourth-strike.com
bandcamp:
  url: fourth-strike.bandcamp.com
  additional_albums:
    - https://sigfigscollective.bandcamp.com/album/voxes-stimulant
    - https://sigfigscollective.bandcamp.com/album/voxes-somnolent
    - https://sigfigscollective.bandcamp.com/album/significant-figures-20
    - https://sigfigscollective.bandcamp.com/track/jet-black-shadow
    - https://sigfigscollective.bandcamp.com/track/seed-guy-war-guy
    - https://sigfigscollective.bandcamp.com/album/sucrosi-road-king-size
    - https://leftatlondon.bandcamp.com/album/t-i-a-p-f-y-h
  single_track_albums:
    - https://sigfigscollective.bandcamp.com/track/jet-black-shadow
    - https://sigfigscollective.bandcamp.com/track/seed-guy-war-guy
  # Some bandcamp skus don't match the home sheet
  merch_sku_remaps:
    BTM-BHHS: T-BHH # "BRUSHED HIS HAND" SWEATSHIRT
    BTM-ISNE: M-INE # IT'S NOT EASY - COLOR-CHANGING MUG
    BTM-KFTP: T-KFP # KILLER FOR THE PIES TEE
    BTM-TDOS: T-DST # THE DEATHS OF SEBASTIAN TELEPHONE TEE
    BTM-TDOS-1: P-DST # The Deaths of Sebastian Telephone [12x12]
    CON-001: C-CON-001 # CASSETTE, CON-001 [RESTOCK]
    FSR-DB22-Tee: T-DB22 # COYOTE WALL X THE GARAGES DB 2022 UNISEX TEE
    P-LPS: P-POSTCS # GARAGES LIVE POSTCARD SET
    P-UND: P-UNDG # UNDERGROUND POSTER
    T-GCR: T-GEC # gender chores - rainbow logo tee
    T-GVD-FIT: T-GVD # THE GARAGES VS DESERT BUS - FITTED TEE
    T-GVD-UNI: T-GVD # THE GARAGES VS DESERT BUS - UNISEX TEE
    TG-CWAT: C-WTB-001 # CASSETTE, "WE ARE THE BAND"
    TG-D8T: T-DEI-80 # DEICIDE - 80s TEE
    TG-KTG8: T-KTG-80 # KILL THE GODS - 80s TEE
    TG-LDBF: T-LADB # LIVE @ DESERT BUS FOR HOPE - TEE
    TG-NF-PCN0: C-NEO-001 # CASSETTE, NEO-001
    TG-PCBO: C-BOB-001 # CASSETTE, "BLATTLE OF THE BLANDS"
    TG-SGLT: T-SGL # SEATTLE GARAGES LOGO TEE
    TG-WATB: T-WTB # WE ARE THE BAND TEE

    SFC-SFCT-CS: T-SFC # SIGNIFICANT FIGURES (CLASSIC) - TEE
    SFC-SFPT-CS: T-SFP # SIG FIGS PENTAGRAM - TEE
    T-STIM: T-STM # STIMULANT - HOODIE
    T-SOMN: T-SOM # SOMNOLENT - HOODIE
    T-SFCA: SFC-SAT # SFC Anniversary Tee

  # Albums that we are explicitly ignoring
  skip_releases:
    # TODO: confirm these:
    - https://garlicbreadandroses.bandcamp.com/album/take-care-of-yourself
  skip_merch: []
  load_merch_from_sales:
    "https://sigfigscollective.bandcamp.com/merch/significant-figures-classic-tee":
      album: null # Significant Figures 2.0 ??
      sku: T-SFC
      list_price: '$23.33'
      private: true
    "https://sigfigscollective.bandcamp.com/merch/sig-figs-pentagram-tee":
      album: null # Significant Figures 2.0 ??
      sku: T-SFP
      list_price: '$23.33'
      private: true
    "https://sigfigscollective.bandcamp.com/merch/stimulant-hoodie":
      album: 'Voxes: Stimulant'
      sku: T-STM
      list_price: '$41.11'
      private: true
    "https://sigfigscollective.bandcamp.com/merch/somnolent-hoodie":
      album: 'Voxes: Somnolent'
      sku: T-SOM
      list_price: '$41.11'
      private: true
    "https://sigfigscollective.bandcamp.com/merch/sfc-anniversary-tee":
      album: null
      sku: T-SFCA
      list_price: '$23.33'
      private: true
    "https://sigfigscollective.bandcamp.com/merch/sfc-sticker-collection-1":
      album: null
      sku: S-SFSP1
      list_price: '$23.33'
      private: true

  # Manually fix Bandcamp sale that wasn't in USD. There's only one, from Sept 2020, when the conversion rate was 1USD = 0.7790GBP
  currency_corrections:
    '1685538022': 0.7790
  merch_skus:
    # SKUs have variant information such as size appended to them, but these merch items represent the product as a whole.
    # We'll go through each of these regexes, finding the first that match and returning the first partial match group as the true sku
    strip_variants:
      # The BTM release, the t-shirt and poster have very similar skus that don't follow the pattern and are hard to differentiate
      - '\A(BTM-TDOS-1)\z' # poster
      - '\A(BTM-TDOS-S)(-[1-3])?\z' # t-shirt
      # Consumed appears as both with C- prefix and without
      - '(CON-001)\z'
      # For this one t-shirt, the unisex and fitted are different urls
      - '\A(T-GVD-(FIT|UNI))-(S|M|L|XL|XXL|XXXL)\z'
      # for cassettes, include the trailing release number
      - '\A(C-[A-Z0-9]{3}-[0-9]{3})\z'
      # For everything else, just grab the first 2 parts
      - '\A([A-Z]{1,3}-[A-Z0-9\+]{3,4})'


  # Tracks/Albums that used to exist at one point and have been replaced with a different version.
  # Treats all the left-hand side ones as equivalent to the right-hand side
  remaps:
    "https://thegarages.bandcamp.com/track/tiana-cash": https://thegarages.bandcamp.com/track/tiana-cash-2
    "https://thegarages.bandcamp.com/album/about-a-squirrel": https://thegarages.bandcamp.com/track/about-a-squirrel-2
    "https://thegarages.bandcamp.com/track/gwiffins-here": https://thegarages.bandcamp.com/track/gwiffins-here-2
    "https://thegarages.bandcamp.com/track/garagesong": https://thegarages.bandcamp.com/track/garagesong-2
    "https://thegarages.bandcamp.com/track/heart-shaped-hotdog": https://thegarages.bandcamp.com/track/heart-shaped-hotdog-2
    "https://thegarages.bandcamp.com/track/ron-monstera-fundamentals": https://thegarages.bandcamp.com/track/ron-monstera-fundamentals-2
    "https://thegarages.bandcamp.com/album/the-mike-townsend-trilogy-2": https://thegarages.bandcamp.com/album/the-mike-townsend-quintilogy
    "https://thegarages.bandcamp.com/album/strike-two": https://fourth-strike.bandcamp.com/album/strike-two
    "https://thegarages.bandcamp.com/album/discipline-2": https://thegarages.bandcamp.com/album/discipline
    "https://thegarages.bandcamp.com/track/mike-townsend-is-a-disappointment": https://thegarages.bandcamp.com/track/mike-townsend-is-a-disappointment-5

  missing_albums:
    - name: 'LIMITER: RELEASED'
      artist_name: the garages
      release_date: '2020-09-04'
      upcs: []
      bandcamp_id: null # I guess because it's private?
      private: true
      bandcamp_url: https://thegarages.bandcamp.com/album/limiter-released
      album_art_url: https://f4.bcbits.com/img/a1715511433_10.jpg
      bandcamp_price: '$0.00'
      tracks:
        - name: 'LIMITER: RELEASED'
          track_number: 1
          bandcamp_id: 465686136
          bandcamp_url: https://thegarages.bandcamp.com/track/limiter-released
          credits: track by rain (rainrain.bandcamp.com) with backing vocals by mucusqueen
          lyrics: >
            theodore duende here, can you answer my call?
            i'm waiting in the wings to go, to go, i'm waiting in the wings
            and i can feel, the blood is pumping through me like
            the engine oil, and all the neurons won't stop firing
            all the neurons won't stop firing

            lift the limit
            now we're in it
            the reverb got us feeling like a new band
            like a new band
            lift the limit
            now we're in it
            the reverb got us feeling like a new band
            like a new band
            with a limiter released

            theodore duende here, my adrenaline is high
            and all the fires in my heart are lit from pheonixes that once flied
            and i can feel magnesium in my veins
            and i can feel the power I get from everyone who cheers my name
        - name: 'in the feedback'
          track_number: 2
          bandcamp_id: 1814415384
          bandcamp_url: https://thegarages.bandcamp.com/track/in-the-feedback
          credits: track by rain (rainrain.bandcamp.com) with additional guitar by zandterbird (@zandterbird)
          lyrics: >
            i can see the truth in your eyes
            as you're telling me lies
            like you know that you'll hold my hand again
            cause you don't know you will
            but i know how you feel
            and i don't know if i can watch you walk out on the field

            and there's the lightning strike
            across the pitch-black night
            and i wanna hold you close, but i can't

            i don't wanna let you go
            in the feedback
            cause i don't know i'd get you back
            yeah, i don't know i'd get you back
            i don't wanna let you go
            in the feedback
            cause i don't know i'd get you back
            yeah, i don't know i'd get you back

            i can feel you pull away from me
            i can feel you retreat
            "duty calls" you say, and then it's
            all of the eyes on the pitcher throwing
            and it's all of the eyes on the way it's going
            and you hit the ball, and then it's out of our hands

            and there's the lightning strike
            across the pitch-black night
            and i wanna hold you close, but i can't

            i don't wanna let you go
            in the feedback
            cause i don't know i'd get you back
            yeah, i don't know i'd get you back
            i don't wanna let you go
            in the feedback
            cause i don't know i'd get you back
            yeah, i don't know i'd get you back

            and there's the lightning strike
            across the pitch-black night
            and then the smoke obscures
            the place where you once stood
            and when it clears, you're just not there

distrokid:
  skip:
    artists: []
home_sheet:
  payees:
    charities:
      - FS-048 # the 343
      - FS-047 # Rainbow Railroad
      - FS-046 # NAMI
      - FS-032 # Child's Play
      - FS-031 # ACLU
  splits:
    overrides:
      # Hard-code split for child's play
      "https://thegarages.bandcamp.com/album/the-garages-vs-desert-bus-2021":
        'FS-032': 1
      "https://fourth-strike.bandcamp.com/album/coyote-wall-x-the-garages-desert-bus-2022":
        'FS-032': 1
    album_mappings:
      # When the album names in the home sheet don't match by name
      'the mike townsend trilogy': https://thegarages.bandcamp.com/album/the-mike-townsend-quintilogy
      'THE GARAGES 101': https://thegarages.bandcamp.com/album/the-garages-101
      'STRIKE TWO!!': https://fourth-strike.bandcamp.com/album/strike-two
      'Putrid Shark #1': https://putridshark.bandcamp.com/album/2
      'BTM / TDOST': https://blaseballmusical.bandcamp.com/album/the-deaths-of-sebastian-telephone
    skip_albums:
      - full digital discography (40 releases)
      - full digital discography (41 releases)
      - full digital discography (42 releases)
      - full digital discography (43 releases)
      - full digital discography (44 releases)
      - full digital discography (45 releases)
      - full digital discography (46 releases)
      - full digital discography (47 releases)
      - full digital discography (48 releases)
      - full digital discography (49 releases)
      - full digital discography (50 releases)
      - full digital discography (51 releases)
      - full digital discography (52 releases)
      - full digital discography (53 releases)
      - full digital discography (54 releases)
      - full digital discography (55 releases)
      - full digital discography (56 releases)
      # TODO: confirm these:
      - ron monstera (fundamentals)
      - Unnamed Gender Chores Release
      - ashes
      - My Baby Wouldn't Pass a Turing Test
    skip_tracks: []
    skip_merch:
      - FSR-001 # tiapfyh, duplicate of C-TPH-001
      # Unsure what this is TODO
      - T-RVS
  merch:
    # deleted?
    - name: FOURTH STRIKE STICKER
      artist_name: Fourth Strike Records
      bandcamp_url: https://fourth-strike.bandcamp.com/merch/fourth-strike-sticker
      sku: FSR-FSS
      list_price: '$1.11'
      private: true
      variants: []
      album: null
    # Sold via iam8bit
    - name: DISCIPLINE Vinyl
      artist_name: the garages
      bandcamp_url: ''
      sku: V-DSP
      list_price: '$46.98'
      private: true
      variants: []
      album: DISCIPLINE
      external_distributor: 'iam8bit'
    # Only seems to have been produced for the patreon
    - name: CASSETTE - LIVE (1993)
      artist_name: the garages
      bandcamp_url: ''
      sku: C-L93-001
      list_price: '$23.33'
      private: true
      variants: []
      album: 'the garages: RIV'
    - name: UNSTABLE - TEE
      artist_name: the garages
      bandcamp_url: ''
      sku: T-UNS
      list_price: '$23.33'
      private: true
      variants: [] # TODO?
      album: UNSTABLE
    - name: Putrid Shark - TEE
      artist_name: Putrid Shark
      bandcamp_url: ''
      sku: T-PUT
      list_price: '$23.33'
      private: true
      variants: [] # TODO? TRANS / CLASSIC / PUTRID
      album: '#2'
    - name: CASSETTE - t.i.a.p.f.y.h.
      artist_name: Left At London
      bandcamp_url: https://leftatlondon.bandcamp.com/album/t-i-a-p-f-y-h
      sku: C-TPH-001
      list_price: '$23.33'
      private: true
      variants: []
      album: "t.i.a.p.f.y.h."
    - name: THE GARAGES CAN'T PLAY LIVE - TEE
      artist_name: the garages
      bandcamp_url: https://thegarages.bandcamp.com/album/the-garages-cant-play-live
      sku: T-CPL
      list_price: '$23.33'
      private: true
      variants: [] # TODO?
      album: "THE GARAGES CAN'T PLAY LIVE"
    - name: I LOVE BIRDS - TEE
      artist_name: Coyote Wall
      bandcamp_url: https://coyotewall.bandcamp.com/album/i-love-birds
      sku: T-ILB
      list_price: '$23.33'
      private: true
      variants: [] # TODO?
      album: "I Love Birds"
  internal_merch:
    sku_remap:
      T-UNDG: T-UND

patreon:
  tiers:
    # No benefits! Just if you wanna help out.
    'No Strikes!':
      digital_distribution: 0.0 # all money goes to FS
      merch: []
    # Get access to sporadic works-in-progress, teases, updates from the
    # Fourth Strike artists, and episodes of idol board a day early!
    'First Strike!':
      digital_distribution: 0.0 # all money goes to FS
      merch: []
    # In addition to demos and teases of what's to come, you'll get a
    # digital download of every release Fourth Strike puts out while you are a patron.
    'Second Strike!':
      # all money treated as digital sales, divided evenly amongst albums
      digital_distribution: 1.0
      merch: []
    # In addition to demo access, and digital downloads, get sent a new t-shirt every month!
    'Third Strike! (T-Shirts)':
      # 12.5% of proceeds are treated as digital sales and divided amongst albums.
      # The rest is treated as a t-shirt merch sale
      digital_distribution: 0.125
      merch: [t-shirt]
    # In addition to demo access, and digital downloads, get sent a new cassette every month!
    'Third Strike! (Cassettes)':
      # 12.5% of proceeds are treated as digital sales and divided amongst albums.
      # The rest is treated as a casette merch sale
      digital_distribution: 0.125
      merch: [cassette]
    # Get demos, WIP teases,a shirt AND a cassette sent to you every month.
    'Fourth Strike!':
      # 7.5% of proceeds are treated as digital sales and divided amongst albums.
      # The rest is treated as a casette merch sale and t-shirt merch sale
      digital_distribution: 0.075
      merch: [cassette, t-shirt]
  products:
    '2021-01-01':
      digital:
        - ROSTER
        - neon fakes
      t-shirt: T-DEI-80 # deicide 80s
      cassette: C-NEO-001 # neon fakes
    '2021-02-01':
      digital:
        - STRIKE ONE!
        - "the garages present: be my vlalentine"
        - "Voxes: Stimulant"
      t-shirt: T-S1T # strike one
      cassette: C-AWY-001 # TODO this is a guess from process of elimination
    '2021-03-01':
      digital:
        - "#14"
        - the garages suck
        - the garages TAKEOVER
      t-shirt: T-TKO # TAKEOVER
      cassette: C-LVB-001 # LIVE (1992)
    '2021-04-01':
      digital:
        - "World Tour: Part 1"
        - "World Tour: Part 2"
        - "UNDEFINED"
        - "THE GARAGES CAN'T PLAY LIVE"
        - "CONSUMED"
      t-shirt: T-CON # CONSUMED
      cassette: C-14+-001 # 14/the garages suck tape
    '2021-05-01':
      digital:
        - storm's here
        - "STRIKE TWO​!​!"
        - Immaterial Shores
        - "Voxes: Somnolent"
        - "where we droppin, boys?"
        - "Tribute Act 2: Headliners"
      t-shirt: T-UND # undefined
      cassette: C-CON-001 # CONSUMED
    '2021-06-01':
      digital:
        - REVERSED
        - "#1"
        - we are the garages (vol 3)
        - spark to a flame
      cassette: C-TPH-001 # tiapfyh
      t-shirt: T-PUT # putrid shark, TRANS / CLASSIC / PUTRID
    '2021-07-01':
      digital:
        - seattle
        - from the shadows
        - UNSTABLE
      t-shirt: T-UNS # UNSTABLE
      cassette: C-UNS-001 # UNSTABLE/REVERSED
    '2021-08-01':
      digital:
        - "#2"
        - "the garages: RIV"
        - "LIVE @ KORPSCON"
      t-shirt: T-RIV # RIV
      cassette: C-PSK-001 # putrid shark 1+2
    '2021-09-01':
      digital:
        - we are the garages (vol 4)
      t-shirt: T-CPL # Can't play live
      cassette: C-L93-001
    '2021-10-01':
      digital:
        - DISCIPLINE
        - Significant Figures 2.0
        - I Love Birds
      t-shirt: T-ILB # I Love Birds
      cassette: C-ILB-001
    '2021-11-01':
      digital:
        - THE GARAGES VS DESERT BUS 2021
        - short circuit 01
      t-shirt: T-GEC
      cassette: C-GEC-001
