organization_name: Fourth Strike
operating_currency: USD
organization_cut: 0.15
services_rendered:
  hourly_rate: 15.00 # USD/hr
payout_at: 42.00 # USD
bandcamp:
  url: fourth-strike.bandcamp.com
  # Some bandcamp skus don't match the home sheet
  merch_sku_remaps:
    BTM-BHHS: T-BHH # "BRUSHED HIS HAND" SWEATSHIRT
    BTM-ISNE: M-INE # IT'S NOT EASY - COLOR-CHANGING MUG
    BTM-KFTP: T-KFP # KILLER FOR THE PIES TEE
    BTM-TDOS: T-DST # THE DEATHS OF SEBASTIAN TELEPHONE TEE
    BTM-TDOS-1: P-DST # The Deaths of Sebastian Telephone [12x12]
    CON-001: C-CON-001 # CASSETTE, CON-001 [RESTOCK]
    FSR-DB22-Tee: T-DB22 # COYOTE WALL X THE GARAGES DB 2022 UNISEX TEE
    P-LPS: P-POSTCS # GARAGES LIVE POSTCARD SET
    P-UND: P-UNDG # UNDERGROUND POSTER
    T-GCR: T-GEC # gender chores - rainbow logo tee
    T-GVD-FIT: T-GVD # THE GARAGES VS DESERT BUS - FITTED TEE
    T-GVD-UNI: T-GVD # THE GARAGES VS DESERT BUS - UNISEX TEE
    TG-CWAT: C-WTB-001 # CASSETTE, "WE ARE THE BAND"
    TG-D8T: T-DEI-80 # DEICIDE - 80s TEE
    TG-KTG8: T-KTG-80 # KILL THE GODS - 80s TEE
    TG-LDBF: T-LADB # LIVE @ DESERT BUS FOR HOPE - TEE
    TG-NF-PCN0: C-NEO-001 # CASSETTE, NEO-001
    TG-PCBO: C-BOB-001 # CASSETTE, "BLATTLE OF THE BLANDS"
    TG-SGLT: T-SGL # SEATTLE GARAGES LOGO TEE
    TG-WATB: T-WTB # WE ARE THE BAND TEE
  # Albums that we are explicitly ignoring
  skip_releases:
    - https://fourth-strike.bandcamp.com/album/fourth-strike-song-jam-2023
    - https://fourth-strike.bandcamp.com/album/fourth-strike-song-jam-2022
    - https://fourth-strike.bandcamp.com/album/fourth-strike-song-jam-2021
    - https://sigfigscollective.bandcamp.com/album/voxes-stimulant
    - https://sigfigscollective.bandcamp.com/album/voxes-somnolent
    - https://sigfigscollective.bandcamp.com/album/significant-figures-20
    - https://sigfigscollective.bandcamp.com/track/jet-black-shadow
    - https://sigfigscollective.bandcamp.com/track/seed-guy-war-guy
    - https://sigfigscollective.bandcamp.com/album/sucrosi-road-king-size
    # TODO: confirm these:
    - https://garlicbreadandroses.bandcamp.com/album/take-care-of-yourself
    - https://thegarages.bandcamp.com/album/limiter-released
  skip_merch:
    - "https://sigfigscollective.bandcamp.com/merch/significant-figures-classic-tee"
    - "https://sigfigscollective.bandcamp.com/merch/sig-figs-pentagram-tee"
    - "https://sigfigscollective.bandcamp.com/merch/stimulant-hoodie"
    - "https://sigfigscollective.bandcamp.com/merch/somnolent-hoodie"
    - "https://sigfigscollective.bandcamp.com/merch/sfc-anniversary-tee"
    - "https://sigfigscollective.bandcamp.com/merch/sfc-sticker-collection-1"

  # Manually fix Bandcamp sale that wasn't in USD. There's only one, from Sept 2020, when the conversion rate was 1USD = 0.7790GBP
  currency_corrections:
    '1685538022': 0.7790
  merch_skus:
    # SKUs have variant information such as size appended to them, but these merch items represent the product as a whole.
    # We'll go through each of these regexes, finding the first that match and returning the first partial match group as the true sku
    strip_variants:
      # The BTM release, the t-shirt and poster have very similar skus that don't follow the pattern and are hard to differentiate
      - '\A(BTM-TDOS-1)\z' # poster
      - '\A(BTM-TDOS-S)(-[1-3])?\z' # t-shirt
      # Consumed appears as both with C- prefix and without
      - '(CON-001)\z'
      # For this one t-shirt, the unisex and fitted are different urls
      - '\A(T-GVD-(FIT|UNI))-(S|M|L|XL|XXL|XXXL)\z'
      # for cassettes, include the trailing release number
      - '\A(C-[A-Z0-9]{3}-[0-9]{3})\z'
      # For everything else, just grab the first 2 parts
      - '\A([A-Z]{1,3}-[A-Z0-9\+]{3,4})'


  # Tracks/Albums that used to exist at one point and have been replaced with a different version.
  # Treats all the left-hand side ones as equivalent to the right-hand side
  remaps:
    "https://thegarages.bandcamp.com/track/tiana-cash": https://thegarages.bandcamp.com/track/tiana-cash-2
    "https://thegarages.bandcamp.com/album/about-a-squirrel": https://thegarages.bandcamp.com/track/about-a-squirrel-2
    "https://thegarages.bandcamp.com/track/gwiffins-here": https://thegarages.bandcamp.com/track/gwiffins-here-2
    "https://thegarages.bandcamp.com/track/garagesong": https://thegarages.bandcamp.com/track/garagesong-2
    "https://thegarages.bandcamp.com/track/heart-shaped-hotdog": https://thegarages.bandcamp.com/track/heart-shaped-hotdog-2
    "https://thegarages.bandcamp.com/track/ron-monstera-fundamentals": https://thegarages.bandcamp.com/track/ron-monstera-fundamentals-2
    "https://thegarages.bandcamp.com/album/the-mike-townsend-trilogy-2": https://thegarages.bandcamp.com/album/the-mike-townsend-quintilogy
    "https://thegarages.bandcamp.com/album/strike-two": https://fourth-strike.bandcamp.com/album/strike-two
    "https://thegarages.bandcamp.com/album/discipline-2": https://thegarages.bandcamp.com/album/discipline
    "https://thegarages.bandcamp.com/track/mike-townsend-is-a-disappointment": https://thegarages.bandcamp.com/track/mike-townsend-is-a-disappointment-5

distrokid:
  skip:
    artists:
      - Sig Figs Collective
home_sheet:
  payees:
    charities:
      - FS-048 # the 343
      - FS-047 # Rainbow Railroad
      - FS-046 # NAMI
      - FS-032 # Child's Play
      - FS-031 # ACLU
  splits:
    overrides:
      # Hard-code split for child's play
      "https://thegarages.bandcamp.com/album/the-garages-vs-desert-bus-2021":
        'FS-032': 1
    album_mappings:
      # When the album names in the home sheet don't match by name
      'the mike townsend trilogy': https://thegarages.bandcamp.com/album/the-mike-townsend-quintilogy
      'THE GARAGES 101': https://thegarages.bandcamp.com/album/the-garages-101
      'STRIKE TWO!!': https://fourth-strike.bandcamp.com/album/strike-two
      'Putrid Shark #1': https://putridshark.bandcamp.com/album/2
      'BTM / TDOST': https://blaseballmusical.bandcamp.com/album/the-deaths-of-sebastian-telephone
    skip_albums:
      - "Voxes: Stimulant"
      - "Voxes: Somnolent"
      - Significant Figures 2.0
      - Jet Black Shadow
      - Seed Guy War Guy
      - Fourth Strike Song Jam 2021
      - fourth strike song jam 2022
      - full digital discography (40 releases)
      - full digital discography (41 releases)
      - full digital discography (42 releases)
      - full digital discography (43 releases)
      - full digital discography (44 releases)
      - full digital discography (45 releases)
      - full digital discography (46 releases)
      - full digital discography (47 releases)
      - full digital discography (48 releases)
      - full digital discography (49 releases)
      - full digital discography (50 releases)
      - full digital discography (51 releases)
      - full digital discography (52 releases)
      - full digital discography (53 releases)
      - full digital discography (54 releases)
      - full digital discography (55 releases)
      - full digital discography (56 releases)
      # TODO: confirm these:
      - ron monstera (fundamentals)
      - Unnamed Gender Chores Release
      - ashes
      - My Baby Wouldn't Pass a Turing Test
    skip_tracks:
      # sig figs
      - QZDA52171312
      - QZDA52171313
      - QZDA52171314
      - QZDA52171315
      - QZDA52171316
      - QZDA52171317
      - QZDA52171318
      - QZDA52171319
      - QZDA52171320
      - QZDA52171321
      - QZDA52171322
      - QZDA52171323
      - QZHN72142371
      - QZHN72142372
      - QZHN72142373
      - QZHN72142374
      - QZHN72142375
      - QZHN72142376
      - QZHN72142377
      - QZHN72142378
      - QZHN72142379
      - QZHN72142380
      - QZHN72142381
      - QZHN72142382
      - QZHN72142383
      - QZHN72142384
      - QZHN72142385
      - QZHN72142386
      - QZHN72142387
      - QZHN72142388
      - QZNWS2114811
      - QZNWS2114812
      - QZNWS2114813
      - QZNWS2193235
      - QZNWS2114815
      - QZNWS2114816
      - QZNWS2114817
      - QZNWS2114818
      - QZNWS2114819
      - QZNWS2114820
      - QZNWS2114821
      - QZNWS2114822
      - QZNWS2114823
      - QZNWS2114824
      - QZNWS2114825
      - QZNWS2114826
    skip_merch:
      # sig figs
      - T-SFC
      - T-SFP
      - T-STM
      - T-SOM
      - S-SFSP1
      - T-SFCA
      # L@L
      - FSR-001
      - C-TPH-001
      # Unsure what this is TODO
      - T-RVS
  merch:
    # deleted?
    - name: FOURTH STRIKE STICKER
      artist_name: Fourth Strike Records
      bandcamp_url: https://fourth-strike.bandcamp.com/merch/fourth-strike-sticker
      sku: FSR-FSS
      list_price: '$1.11'
      private: true
      variants: []
      album: null
    # Sold via iam8bit
    - name: DISCIPLINE Vinyl
      artist_name: the garages
      bandcamp_url: null
      sku: V-DSP
      list_price: '$46.98'
      private: true
      variants: []
      album: DISCIPLINE
    - name: CASSETTE - LIVE (1993)
      artist_name: the garages
      bandcamp_url: null
      sku: C-L93-001
      list_price: '$46.98'
      private: true
      variants: []
      album: 'the garages: RIV'
    - name: UNSTABLE - TEE
      artist_name: the garages
      bandcamp_url: null
      sku: T-UNS
      list_price: '$23.33'
      private: true
      variants: [] # TODO?
      album: UNSTABLE
    - name: Putrid Shark - TEE
      artist_name: Putrid Shark
      bandcamp_url: null
      sku: T-PUT
      list_price: '$23.33'
      private: true
      variants: [] # TODO? TRANS / CLASSIC / PUTRID
      album: '#2'
